(cl:defpackage lightswitch-msg
  (:use )
  (:export
   "<LIGHTCONTROLACTION>"
   "LIGHTCONTROLACTION"
   "<LIGHTCONTROLACTIONFEEDBACK>"
   "LIGHTCONTROLACTIONFEEDBACK"
   "<LIGHTCONTROLACTIONGOAL>"
   "LIGHTCONTROLACTIONGOAL"
   "<LIGHTCONTROLACTIONRESULT>"
   "LIGHTCONTROLACTIONRESULT"
   "<LIGHTCONTROLFEEDBACK>"
   "LIGHTCONTROLFEEDBACK"
   "<LIGHTCONTROLGOAL>"
   "LIGHTCONTROLGOAL"
   "<LIGHTCONTROLRESULT>"
   "LIGHTCONTROLRESULT"
  ))

