; Auto-generated. Do not edit!


(cl:in-package lightswitch-msg)


;//! \htmlinclude LightControlFeedback.msg.html

(cl:defclass <LightControlFeedback> (roslisp-msg-protocol:ros-message)
  ((latency
    :reader latency
    :initarg :latency
    :type cl:integer
    :initform 0))
)

(cl:defclass LightControlFeedback (<LightControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LightControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LightControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lightswitch-msg:<LightControlFeedback> is deprecated: use lightswitch-msg:LightControlFeedback instead.")))

(cl:ensure-generic-function 'latency-val :lambda-list '(m))
(cl:defmethod latency-val ((m <LightControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lightswitch-msg:latency-val is deprecated.  Use lightswitch-msg:latency instead.")
  (latency m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LightControlFeedback>) ostream)
  "Serializes a message object of type '<LightControlFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'latency)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LightControlFeedback>) istream)
  "Deserializes a message object of type '<LightControlFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'latency) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LightControlFeedback>)))
  "Returns string type for a message object of type '<LightControlFeedback>"
  "lightswitch/LightControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LightControlFeedback)))
  "Returns string type for a message object of type 'LightControlFeedback"
  "lightswitch/LightControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LightControlFeedback>)))
  "Returns md5sum for a message object of type '<LightControlFeedback>"
  "e0719860029b52fb7235c4419950e357")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LightControlFeedback)))
  "Returns md5sum for a message object of type 'LightControlFeedback"
  "e0719860029b52fb7235c4419950e357")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LightControlFeedback>)))
  "Returns full string definition for message of type '<LightControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%int32 latency~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LightControlFeedback)))
  "Returns full string definition for message of type 'LightControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback~%int32 latency~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LightControlFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LightControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LightControlFeedback
    (cl:cons ':latency (latency msg))
))
