; Auto-generated. Do not edit!


(cl:in-package lightswitch-msg)


;//! \htmlinclude LightControlGoal.msg.html

(cl:defclass <LightControlGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:integer
    :initform 0))
)

(cl:defclass LightControlGoal (<LightControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LightControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LightControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lightswitch-msg:<LightControlGoal> is deprecated: use lightswitch-msg:LightControlGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <LightControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lightswitch-msg:command-val is deprecated.  Use lightswitch-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LightControlGoal>) ostream)
  "Serializes a message object of type '<LightControlGoal>"
  (cl:let* ((signed (cl:slot-value msg 'command)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LightControlGoal>) istream)
  "Deserializes a message object of type '<LightControlGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LightControlGoal>)))
  "Returns string type for a message object of type '<LightControlGoal>"
  "lightswitch/LightControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LightControlGoal)))
  "Returns string type for a message object of type 'LightControlGoal"
  "lightswitch/LightControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LightControlGoal>)))
  "Returns md5sum for a message object of type '<LightControlGoal>"
  "3a54bc0c5f4abe9ad44d29292ec0800d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LightControlGoal)))
  "Returns md5sum for a message object of type 'LightControlGoal"
  "3a54bc0c5f4abe9ad44d29292ec0800d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LightControlGoal>)))
  "Returns full string definition for message of type '<LightControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LightControlGoal)))
  "Returns full string definition for message of type 'LightControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LightControlGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LightControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LightControlGoal
    (cl:cons ':command (command msg))
))
