---
  gpio_pins:
    - 4
    - 17
    - 18
    - 27
    - 22
    - 23
    - 24
    - 12
    - 6
    - 5
    - 11
    - 9
    - 10
    - 25
    - 13
    - 19
    - 16
    - 26
    - 20
    - 21

  timerRate : 5

  
