---
  gpio_pins:
          #    - 4
    - 17
      #    - 18
    - 27
      #    - 22
      #    - 23
      #    - 24
      #    - 9
      #    - 25
      #    - 11
      #    - 8
      #    - 7
      #    - 5
      #    - 6
      #    - 12
      #    - 13
      #    - 19
      #    - 16
      #    - 26
      #    - 20
      #    - 21

  timerRate : 5

  
