// Generated by gencpp from file lightswitch/LightControlFeedback.msg
// DO NOT EDIT!


#ifndef LIGHTSWITCH_MESSAGE_LIGHTCONTROLFEEDBACK_H
#define LIGHTSWITCH_MESSAGE_LIGHTCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lightswitch
{
template <class ContainerAllocator>
struct LightControlFeedback_
{
  typedef LightControlFeedback_<ContainerAllocator> Type;

  LightControlFeedback_()
    : latency(0)  {
    }
  LightControlFeedback_(const ContainerAllocator& _alloc)
    : latency(0)  {
  (void)_alloc;
    }



   typedef int32_t _latency_type;
  _latency_type latency;





  typedef boost::shared_ptr< ::lightswitch::LightControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lightswitch::LightControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct LightControlFeedback_

typedef ::lightswitch::LightControlFeedback_<std::allocator<void> > LightControlFeedback;

typedef boost::shared_ptr< ::lightswitch::LightControlFeedback > LightControlFeedbackPtr;
typedef boost::shared_ptr< ::lightswitch::LightControlFeedback const> LightControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lightswitch::LightControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lightswitch::LightControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lightswitch

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'lightswitch': ['/home/pi/SST_HMI/rpi_ros/devel/share/lightswitch/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lightswitch::LightControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lightswitch::LightControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lightswitch::LightControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e0719860029b52fb7235c4419950e357";
  }

  static const char* value(const ::lightswitch::LightControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe0719860029b52fbULL;
  static const uint64_t static_value2 = 0x7235c4419950e357ULL;
};

template<class ContainerAllocator>
struct DataType< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lightswitch/LightControlFeedback";
  }

  static const char* value(const ::lightswitch::LightControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the feedback\n\
int32 latency\n\
";
  }

  static const char* value(const ::lightswitch::LightControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lightswitch::LightControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lightswitch::LightControlFeedback_<ContainerAllocator>& v)
  {
    s << indent << "latency: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHTSWITCH_MESSAGE_LIGHTCONTROLFEEDBACK_H
