// Generated by gencpp from file lightswitch/LightControlResult.msg
// DO NOT EDIT!


#ifndef LIGHTSWITCH_MESSAGE_LIGHTCONTROLRESULT_H
#define LIGHTSWITCH_MESSAGE_LIGHTCONTROLRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lightswitch
{
template <class ContainerAllocator>
struct LightControlResult_
{
  typedef LightControlResult_<ContainerAllocator> Type;

  LightControlResult_()
    : status()  {
    }
  LightControlResult_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::lightswitch::LightControlResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lightswitch::LightControlResult_<ContainerAllocator> const> ConstPtr;

}; // struct LightControlResult_

typedef ::lightswitch::LightControlResult_<std::allocator<void> > LightControlResult;

typedef boost::shared_ptr< ::lightswitch::LightControlResult > LightControlResultPtr;
typedef boost::shared_ptr< ::lightswitch::LightControlResult const> LightControlResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lightswitch::LightControlResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lightswitch::LightControlResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lightswitch

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'lightswitch': ['/home/pi/SST_HMI/rpi_ros/devel/share/lightswitch/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lightswitch::LightControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lightswitch::LightControlResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lightswitch::LightControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lightswitch::LightControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lightswitch::LightControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lightswitch::LightControlResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lightswitch::LightControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::lightswitch::LightControlResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::lightswitch::LightControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lightswitch/LightControlResult";
  }

  static const char* value(const ::lightswitch::LightControlResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lightswitch::LightControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
string status\n\
";
  }

  static const char* value(const ::lightswitch::LightControlResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lightswitch::LightControlResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightControlResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lightswitch::LightControlResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lightswitch::LightControlResult_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHTSWITCH_MESSAGE_LIGHTCONTROLRESULT_H
